/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccommodationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccommodationApiTests
    {
        private AccommodationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccommodationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccommodationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccommodationApi
            //Assert.IsInstanceOfType(typeof(AccommodationApi), instance, "instance is a AccommodationApi");
        }

        
        /// <summary>
        /// Test AddAccommodation
        /// </summary>
        [Test]
        public void AddAccommodationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //long? capacity = null;
            //int? basePrices = null;
            //string description = null;
            //var response = instance.AddAccommodation(name, capacity, basePrices, description);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test DeleteAccommodation
        /// </summary>
        [Test]
        public void DeleteAccommodationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? body = null;
            //var response = instance.DeleteAccommodation(body);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test EditAgent
        /// </summary>
        [Test]
        public void EditAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //long? name = null;
            //string branchName = null;
            //string branchAddress = null;
            //string branchPhone = null;
            //string branchEmail = null;
            //float? commission = null;
            //string terms = null;
            //string website = null;
            //string billingAddress = null;
            //string billingPhone = null;
            //string billingEmail = null;
            //var response = instance.EditAgent(id, name, branchName, branchAddress, branchPhone, branchEmail, commission, terms, website, billingAddress, billingPhone, billingEmail);
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test FilterAccommodation
        /// </summary>
        [Test]
        public void FilterAccommodationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? before = null;
            //DateTime? after = null;
            //long? accommodationId = null;
            //var response = instance.FilterAccommodation(before, after, accommodationId);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test FindAccommodation
        /// </summary>
        [Test]
        public void FindAccommodationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long?> id = null;
            //var response = instance.FindAccommodation(id);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test GetAllAccommodations
        /// </summary>
        [Test]
        public void GetAllAccommodationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllAccommodations();
            //Assert.IsInstanceOf<List<Accommodation>> (response, "response is List<Accommodation>");
        }
        
        /// <summary>
        /// Test GetAllWithTrashedAccommodations
        /// </summary>
        [Test]
        public void GetAllWithTrashedAccommodationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllWithTrashedAccommodations();
            //Assert.IsInstanceOf<List<Accommodation>> (response, "response is List<Accommodation>");
        }
        
        /// <summary>
        /// Test UpdateAccommodation
        /// </summary>
        [Test]
        public void UpdateAccommodationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string name = null;
            //long? capacity = null;
            //var response = instance.UpdateAccommodation(id, name, capacity);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
    }

}
