/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AgentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AgentApiTests
    {
        private AgentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AgentApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AgentApi
            //Assert.IsInstanceOfType(typeof(AgentApi), instance, "instance is a AgentApi");
        }

        
        /// <summary>
        /// Test CreateAgent
        /// </summary>
        [Test]
        public void CreateAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? name = null;
            //string branchName = null;
            //string branchAddress = null;
            //string branchPhone = null;
            //string branchEmail = null;
            //float? commission = null;
            //string terms = null;
            //string website = null;
            //string billingAddress = null;
            //string billingPhone = null;
            //string billingEmail = null;
            //var response = instance.CreateAgent(name, branchName, branchAddress, branchPhone, branchEmail, commission, terms, website, billingAddress, billingPhone, billingEmail);
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test DeleteAgent
        /// </summary>
        [Test]
        public void DeleteAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.DeleteAgent(id);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test GetAgent
        /// </summary>
        [Test]
        public void GetAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetAgent(id);
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test GetAllAgents
        /// </summary>
        [Test]
        public void GetAllAgentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllAgents();
            //Assert.IsInstanceOf<List<Agent>> (response, "response is List<Agent>");
        }
        
        /// <summary>
        /// Test GetAllWithTrashedAgents
        /// </summary>
        [Test]
        public void GetAllWithTrashedAgentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllWithTrashedAgents();
            //Assert.IsInstanceOf<List<Agent>> (response, "response is List<Agent>");
        }
        
    }

}
