/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ClasssessionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ClasssessionApiTests
    {
        private ClasssessionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ClasssessionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClasssessionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ClasssessionApi
            //Assert.IsInstanceOfType(typeof(ClasssessionApi), instance, "instance is a ClasssessionApi");
        }

        
        /// <summary>
        /// Test ClassSessionGet
        /// </summary>
        [Test]
        public void ClassSessionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.ClassSessionGet(id);
            //Assert.IsInstanceOf<TrainingSession> (response, "response is TrainingSession");
        }
        
        /// <summary>
        /// Test CreateClassSession
        /// </summary>
        [Test]
        public void CreateClassSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? start = null;
            //long? trainingId = null;
            //var response = instance.CreateClassSession(start, trainingId);
            //Assert.IsInstanceOf<InlineResponse20019> (response, "response is InlineResponse20019");
        }
        
        /// <summary>
        /// Test DeleteClasssession
        /// </summary>
        [Test]
        public void DeleteClasssessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.DeleteClasssession(id);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test EditClassSession
        /// </summary>
        [Test]
        public void EditClassSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //DateTime? start = null;
            //var response = instance.EditClassSession(id, start);
            //Assert.IsInstanceOf<InlineResponse20020> (response, "response is InlineResponse20020");
        }
        
        /// <summary>
        /// Test FilterClassSession
        /// </summary>
        [Test]
        public void FilterClassSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FilterClassSession();
            //Assert.IsInstanceOf<List<TrainingSession>> (response, "response is List<TrainingSession>");
        }
        
        /// <summary>
        /// Test GetAllClassSessions
        /// </summary>
        [Test]
        public void GetAllClassSessionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllClassSessions();
            //Assert.IsInstanceOf<List<TrainingSession>> (response, "response is List<TrainingSession>");
        }
        
        /// <summary>
        /// Test GetAllWithTrashedClassSessions
        /// </summary>
        [Test]
        public void GetAllWithTrashedClassSessionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllWithTrashedClassSessions();
            //Assert.IsInstanceOf<List<TrainingSession>> (response, "response is List<TrainingSession>");
        }
        
        /// <summary>
        /// Test GetClassSessionManifest
        /// </summary>
        [Test]
        public void GetClassSessionManifestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetClassSessionManifest(id);
            //Assert.IsInstanceOf<TrainingSessionManifest> (response, "response is TrainingSessionManifest");
        }
        
        /// <summary>
        /// Test GetTodaysClassSession
        /// </summary>
        [Test]
        public void GetTodaysClassSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTodaysClassSession();
            //Assert.IsInstanceOf<List<TrainingSession>> (response, "response is List<TrainingSession>");
        }
        
        /// <summary>
        /// Test GetTommorowsClassSession
        /// </summary>
        [Test]
        public void GetTommorowsClassSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTommorowsClassSession();
            //Assert.IsInstanceOf<List<TrainingSession>> (response, "response is List<TrainingSession>");
        }
        
    }

}
