/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CustomerApiTests
    {
        private CustomerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CustomerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CustomerApi
            //Assert.IsInstanceOfType(typeof(CustomerApi), instance, "instance is a CustomerApi");
        }

        
        /// <summary>
        /// Test CreateCustomer
        /// </summary>
        [Test]
        public void CreateCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //string firstname = null;
            //string lastname = null;
            //DateTime? birthday = null;
            //int? gender = null;
            //string address1 = null;
            //string address2 = null;
            //string city = null;
            //string county = null;
            //string postcode = null;
            //long? countryId = null;
            //string phone = null;
            //DateTime? lastDive = null;
            //int? numberOfDives = null;
            //string chestSize = null;
            //string showSize = null;
            //string height = null;
            //List<long?> certificates = null;
            //var response = instance.CreateCustomer(email, firstname, lastname, birthday, gender, address1, address2, city, county, postcode, countryId, phone, lastDive, numberOfDives, chestSize, showSize, height, certificates);
            //Assert.IsInstanceOf<InlineResponse20029> (response, "response is InlineResponse20029");
        }
        
        /// <summary>
        /// Test DeleteCustomer
        /// </summary>
        [Test]
        public void DeleteCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.DeleteCustomer(id);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test EditCustomer
        /// </summary>
        [Test]
        public void EditCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string email = null;
            //string firstname = null;
            //string lastname = null;
            //DateTime? birthday = null;
            //int? gender = null;
            //string address1 = null;
            //string address2 = null;
            //string city = null;
            //string county = null;
            //string postcode = null;
            //long? countryId = null;
            //string phone = null;
            //DateTime? lastDive = null;
            //int? numberOfDives = null;
            //string chestSize = null;
            //string showSize = null;
            //string height = null;
            //List<long?> certificates = null;
            //var response = instance.EditCustomer(id, email, firstname, lastname, birthday, gender, address1, address2, city, county, postcode, countryId, phone, lastDive, numberOfDives, chestSize, showSize, height, certificates);
            //Assert.IsInstanceOf<InlineResponse20030> (response, "response is InlineResponse20030");
        }
        
        /// <summary>
        /// Test GetAllCustomers
        /// </summary>
        [Test]
        public void GetAllCustomersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllCustomers();
            //Assert.IsInstanceOf<List<Customer>> (response, "response is List<Customer>");
        }
        
        /// <summary>
        /// Test GetCustomer
        /// </summary>
        [Test]
        public void GetCustomerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetCustomer(id);
            //Assert.IsInstanceOf<InlineResponse20029> (response, "response is InlineResponse20029");
        }
        
    }

}
