/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TicketApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TicketApiTests
    {
        private TicketApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TicketApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TicketApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TicketApi
            //Assert.IsInstanceOfType(typeof(TicketApi), instance, "instance is a TicketApi");
        }

        
        /// <summary>
        /// Test AddTicket
        /// </summary>
        [Test]
        public void AddTicketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //List<long?> trips = null;
            //BasePrice prices = null;
            //string description = null;
            //DateTime? availableFrom = null;
            //DateTime? availableUntil = null;
            //bool? onlyPackaged = null;
            //List<long?> boats = null;
            //List<long?> boatrooms = null;
            //var response = instance.AddTicket(name, trips, prices, description, availableFrom, availableUntil, onlyPackaged, boats, boatrooms);
            //Assert.IsInstanceOf<InlineResponse2014> (response, "response is InlineResponse2014");
        }
        
        /// <summary>
        /// Test DeleteTicket
        /// </summary>
        [Test]
        public void DeleteTicketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.DeleteTicket(name);
            //Assert.IsInstanceOf<InlineResponse2014> (response, "response is InlineResponse2014");
        }
        
        /// <summary>
        /// Test EditTicket
        /// </summary>
        [Test]
        public void EditTicketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string name = null;
            //List<long?> trips = null;
            //BasePrice prices = null;
            //string description = null;
            //DateTime? availableFrom = null;
            //DateTime? availableUntil = null;
            //bool? onlyPackaged = null;
            //List<long?> boats = null;
            //List<long?> boatrooms = null;
            //var response = instance.EditTicket(id, name, trips, prices, description, availableFrom, availableUntil, onlyPackaged, boats, boatrooms);
            //Assert.IsInstanceOf<InlineResponse2014> (response, "response is InlineResponse2014");
        }
        
        /// <summary>
        /// Test GetAllAvailableTickets
        /// </summary>
        [Test]
        public void GetAllAvailableTicketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllAvailableTickets();
            //Assert.IsInstanceOf<List<Ticket>> (response, "response is List<Ticket>");
        }
        
        /// <summary>
        /// Test GetAllTickets
        /// </summary>
        [Test]
        public void GetAllTicketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllTickets();
            //Assert.IsInstanceOf<List<Ticket>> (response, "response is List<Ticket>");
        }
        
        /// <summary>
        /// Test GetAllWithTrashedTickets
        /// </summary>
        [Test]
        public void GetAllWithTrashedTicketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllWithTrashedTickets();
            //Assert.IsInstanceOf<List<Ticket>> (response, "response is List<Ticket>");
        }
        
        /// <summary>
        /// Test GetTicket
        /// </summary>
        [Test]
        public void GetTicketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetTicket(id);
            //Assert.IsInstanceOf<Ticket> (response, "response is Ticket");
        }
        
    }

}
