/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TimetableApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TimetableApiTests
    {
        private TimetableApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TimetableApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimetableApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TimetableApi
            //Assert.IsInstanceOfType(typeof(TimetableApi), instance, "instance is a TimetableApi");
        }

        
        /// <summary>
        /// Test AddTimetable
        /// </summary>
        [Test]
        public void AddTimetableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string schedule = null;
            //long? sessionId = null;
            //DateTime? until = null;
            //var response = instance.AddTimetable(schedule, sessionId, until);
            //Assert.IsInstanceOf<InlineResponse2015> (response, "response is InlineResponse2015");
        }
        
        /// <summary>
        /// Test GetAllTimetables
        /// </summary>
        [Test]
        public void GetAllTimetablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllTimetables();
            //Assert.IsInstanceOf<List<Timetable>> (response, "response is List<Timetable>");
        }
        
        /// <summary>
        /// Test GetTimetable
        /// </summary>
        [Test]
        public void GetTimetableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetTimetable(id);
            //Assert.IsInstanceOf<Timetable> (response, "response is Timetable");
        }
        
    }

}
