/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20042
    /// </summary>
    [DataContract]
    public partial class InlineResponse20042 :  IEquatable<InlineResponse20042>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20042" /> class.
        /// </summary>
        /// <param name="Daterange">Daterange.</param>
        /// <param name="Utilisation">Utilisation.</param>
        /// <param name="UtilisationTotals">UtilisationTotals.</param>
        public InlineResponse20042(DateRange Daterange = null, InlineResponse20042Utilisation Utilisation = null, InlineResponse20042UtilisationTotals UtilisationTotals = null)
        {
            this.Daterange = Daterange;
            this.Utilisation = Utilisation;
            this.UtilisationTotals = UtilisationTotals;
        }
        
        /// <summary>
        /// Gets or Sets Daterange
        /// </summary>
        [DataMember(Name="daterange", EmitDefaultValue=false)]
        public DateRange Daterange { get; set; }
        /// <summary>
        /// Gets or Sets Utilisation
        /// </summary>
        [DataMember(Name="utilisation", EmitDefaultValue=false)]
        public InlineResponse20042Utilisation Utilisation { get; set; }
        /// <summary>
        /// Gets or Sets UtilisationTotals
        /// </summary>
        [DataMember(Name="utilisation_totals", EmitDefaultValue=false)]
        public InlineResponse20042UtilisationTotals UtilisationTotals { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20042 {\n");
            sb.Append("  Daterange: ").Append(Daterange).Append("\n");
            sb.Append("  Utilisation: ").Append(Utilisation).Append("\n");
            sb.Append("  UtilisationTotals: ").Append(UtilisationTotals).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponse20042);
        }

        /// <summary>
        /// Returns true if InlineResponse20042 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20042 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20042 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Daterange == other.Daterange ||
                    this.Daterange != null &&
                    this.Daterange.Equals(other.Daterange)
                ) && 
                (
                    this.Utilisation == other.Utilisation ||
                    this.Utilisation != null &&
                    this.Utilisation.Equals(other.Utilisation)
                ) && 
                (
                    this.UtilisationTotals == other.UtilisationTotals ||
                    this.UtilisationTotals != null &&
                    this.UtilisationTotals.Equals(other.UtilisationTotals)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Daterange != null)
                    hash = hash * 59 + this.Daterange.GetHashCode();
                if (this.Utilisation != null)
                    hash = hash * 59 + this.Utilisation.GetHashCode();
                if (this.UtilisationTotals != null)
                    hash = hash * 59 + this.UtilisationTotals.GetHashCode();
                return hash;
            }
        }
    }

}
