/* 
 * Scubawhere API Documentation
 *
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Booking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookingTests
    {
        // TODO uncomment below to declare an instance variable for Booking
        //private Booking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Booking
            //instance = new Booking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Booking
        /// </summary>
        [Test]
        public void BookingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Booking
            //Assert.IsInstanceOfType<Booking> (instance, "variable 'instance' is a Booking");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'LeadCustomerId'
        /// </summary>
        [Test]
        public void LeadCustomerIdTest()
        {
            // TODO unit test for the property 'LeadCustomerId'
        }
        /// <summary>
        /// Test the property 'AgentId'
        /// </summary>
        [Test]
        public void AgentIdTest()
        {
            // TODO unit test for the property 'AgentId'
        }
        /// <summary>
        /// Test the property 'AgentReference'
        /// </summary>
        [Test]
        public void AgentReferenceTest()
        {
            // TODO unit test for the property 'AgentReference'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ReservedUntil'
        /// </summary>
        [Test]
        public void ReservedUntilTest()
        {
            // TODO unit test for the property 'ReservedUntil'
        }
        /// <summary>
        /// Test the property 'CancellationFee'
        /// </summary>
        [Test]
        public void CancellationFeeTest()
        {
            // TODO unit test for the property 'CancellationFee'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Test]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'DecimalPrice'
        /// </summary>
        [Test]
        public void DecimalPriceTest()
        {
            // TODO unit test for the property 'DecimalPrice'
        }
        /// <summary>
        /// Test the property 'RealDecimalPrice'
        /// </summary>
        [Test]
        public void RealDecimalPriceTest()
        {
            // TODO unit test for the property 'RealDecimalPrice'
        }
        /// <summary>
        /// Test the property 'ArrivalDate'
        /// </summary>
        [Test]
        public void ArrivalDateTest()
        {
            // TODO unit test for the property 'ArrivalDate'
        }
        /// <summary>
        /// Test the property 'CreatedAtLocal'
        /// </summary>
        [Test]
        public void CreatedAtLocalTest()
        {
            // TODO unit test for the property 'CreatedAtLocal'
        }
        /// <summary>
        /// Test the property 'LeadCustomer'
        /// </summary>
        [Test]
        public void LeadCustomerTest()
        {
            // TODO unit test for the property 'LeadCustomer'
        }
        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Test]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }
        /// <summary>
        /// Test the property 'Refunds'
        /// </summary>
        [Test]
        public void RefundsTest()
        {
            // TODO unit test for the property 'Refunds'
        }

    }

}
